### ISSUE TITLE
please delete :) 

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#100]
![Untitled](https://user-images.githubusercontent.com/79367027/119697675-11ac6200-be16-11eb-8837-0c13a2d01703.png)

**Comment by JacobWeisenburger** [comment]
as soon as you turn on the other computers, I can do this

**Comment by RoyalDrive** [comment]
All 3 computers in the office are turned on now! :)

**Comment by JacobWeisenburger** [comment]
done
