### ISSUE TITLE
Email copy template

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#103]
Email Template
---
Hi FIRSTNAME,

The `{{description}}` 2018 HYUNDAI KONA SE AWD is still available!

We're open Mon-Fri 9-5pm and Saturdays until 4pm. Please call or text if you have any questions or visit us for a test drive!

Call or text: 651-447-7908

`{{weblink}}` https://www.royaldriveautos.com/details/used-2018-hyundai-kona/69875022

**Comment by JacobWeisenburger** [comment]
Please copy the template that you use right now or an example into here. Don't worry about changing the data into the variable names, I can do that. I just need something to go on.

**Comment by RoyalDrive** [comment]
Hi FIRSTNAME,

The vehicle is still available!

We're open Mon-Fri 9-5pm and Saturdays until 4pm. Please call or text if you have any questions or visit us for a test drive!

Call or text: 651-447-7908

https://www.royaldriveautos.com/details/used-2018-hyundai-kona/69875022

**Comment by JacobWeisenburger** [comment]
How does this look?

---
Hi FIRSTNAME,

The `{{description}}` 2018 HYUNDAI KONA SE AWD is still available!

We're open Mon-Fri 9-5pm and Saturdays until 4pm. Please call or text if you have any questions or visit us for a test drive!

Call or text: 651-447-7908

`{{weblink}}` https://www.royaldriveautos.com/details/used-2018-hyundai-kona/69875022

**Comment by RoyalDrive** [comment]
LOVE IT
