### ISSUE TITLE
New section: Customer Info

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#105]
## New section below Sale: Customer
- Name: `text field`
- Phone: `text field`
- Email: `text field`
- Post-Sale Email: `date picker`

![image](https://user-images.githubusercontent.com/79367027/147589154-a87b8f28-a8d8-47a6-b8d1-e28e27028bf9.png)

**Comment by JacobWeisenburger** [comment]
What is the Post-Sale Email trying to track? If the customer wants to receive emails in the future? Or if the customer has/hasn't been sent a receipt/sale confirmation?

**Comment by RoyalDrive** [comment]
It's just a note to the sales rep if we sent out the post-sale thank you email yet or if we still have to.

**Comment by JacobWeisenburger** [comment]
Would it be ok if that was a date picker that shows the day you sent the email?

**Comment by RoyalDrive** [comment]
Yes - even better idea!

**Comment by RoyalDrive** [comment]
Awesome! Thank you!

Timothy Befus
Office Manager


i ***@***.******@***.***
www.royaldriveautos.com
1412 Hastings Avenue
Newport, MN 55055
Call or text: 651-447-7908
