### ISSUE TITLE
Role Based Access

### ISSUE THREAD

**Issue by JacobWeisenburger** [Royal-Drive/DMS#106]
## Users
Name | Email | Role
-- | -- | --
Royal Drive | info@royaldriveautos.com | Manager
Accountant | { need email } | Viewer
Fernando Ramirez | rfernando.55055@gmail.com | Onsite Technician

## Access Roles
<table>
<tr><th></th><th>Role</th><th>Page</th><th>Access</th></tr>
<tr><td rowspan=5>Logged In</td></tr>
<tr><td>Manager</td><td>All</td><td>Full</td></tr>
<tr><td>Viewer</td><td>All</td><td>View Only</td></tr>
<tr><td rowspan=2>Onsite Technician</td><td>Car List</td><td>Onsite Repair filter only</td></tr>
<tr><td>Car Details</td><td>View Only Specific Fields (see below) and Add expenses</td></tr>
<tr><td rowspan=1>Not Logged In</td><td>Guest</td><td>Login</td><td>View Only</td></tr>
</table>

---
Onsite Technician View Only Fields:
- VIN
- Lot Number
- Year
- Make
- Model
- Trim
- Odometer
- Color

---
#### Expanded from:
Visibility & Edit access for On-Site Repair filter only #95

**Comment by RoyalDrive** [comment]
New Role to include: Accountant (view access on all pages, but no edit access)

**Comment by JacobWeisenburger** [comment]
Users and Access Roles updated. Please check that it matches what you are wanting.

**Comment by RoyalDrive** [comment]
Looking good! A couple edits:

Can we change the name of Onsite Repairman to Onsite Technician? 

Onsite Repairman looks good for pages to access. For the Car Details please remove visibility to all sections except vehicle details (excluding sensitive information such as price) and the ability to add expenses but not remove. 

So it should look something like this for the mechanic: 

![image](https://user-images.githubusercontent.com/79367027/177800951-be47a2be-de0e-4bd4-be62-cb3dac8ef318.png)
![image](https://user-images.githubusercontent.com/79367027/177800990-62bad724-71ef-4d42-88d6-e747aa6bb6ee.png)

**Comment by RoyalDrive** [comment]
Also, for a guest who is not yet logged in please remove visibility to any pages or information other than a login page.

**Comment by JacobWeisenburger** [comment]
> Looking good! A couple edits:
> 
> Can we change the name of Onsite Repairman to Onsite Technician?
> 
> Onsite Repairman looks good for pages to access. For the Car Details please remove visibility to all sections except vehicle details (excluding sensitive information such as price) and the ability to add expenses but not remove.
> 
> So it should look something like this for the mechanic:
> 
> ![image](https://user-images.githubusercontent.com/79367027/177800951-be47a2be-de0e-4bd4-be62-cb3dac8ef318.png) ![image](https://user-images.githubusercontent.com/79367027/177800990-62bad724-71ef-4d42-88d6-e747aa6bb6ee.png)

updated

**Comment by JacobWeisenburger** [comment]
Is it very important for the Onsite Technician to be able to add Expenses?

**Comment by JacobWeisenburger** [comment]
I will need some info so I can make the new user accounts. Then this feature will be done.

![image](https://user-images.githubusercontent.com/31667350/180836667-97b23dcd-e956-40f9-ac49-9dc0fcdb34c9.png)

**Comment by RoyalDrive** [comment]
Onsite Technician does not need to be able to add expenses.

Accountant:
Rochelle Simonson
rsimonson@woodcpamn.com

Fernando Ramirez
rfernando.55055@gmail.com

**Comment by JacobWeisenburger** [comment]
currently, the DMS only allows google accounts to sign in, so Rochelle will need to use a google account or make [rsimonson@woodcpamn.com](mailto:rsimonson@woodcpamn.com) into a google account.

**Comment by RoyalDrive** [comment]
I can ask.

**Comment by JacobWeisenburger** [comment]
This feature is now live. Let me know if I should use a different email for your accountant when she get's back to you.
