### ISSUE TITLE
Days Owned Reporting Feature

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#116]
Additional feature to add to the reporting page:

**DAYS OWNED**
- average days owned of all cars sold between selected months 
- shortest days owned from purchased to sold (displaying the specific vehicle would be a bonus)
- longest days owned (displaying the specific vehicle would be a bonus)

**Comment by JacobWeisenburger** [comment]
Almost done with this

**Comment by RoyalDrive** [comment]
😎
