### ISSUE TITLE
More Dynamic Website Template button for cars

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#117]
Hey Jake!

Please update the website template button when you can to the text below

![image](https://user-images.githubusercontent.com/79367027/161388422-9ea724a5-a189-4a2d-b2fe-6cd2c69d83a7.png)

![image](https://user-images.githubusercontent.com/79367027/161391298-751138da-f73f-4c4f-a7cd-9f981fb82da2.png)

TEXT PASTED BELOW FOR EASY COPY/PASTE

Hail Sale! Clean Title! Repaired Tree Dent! Recovered Theft! Trade in! Minor Dent! 
Only display “Hail Sale!” if hail is selected as the vehicle damage
Average price: $20,000. Our price: $16,495.
Is it possible to have the average price be auto calculated to be 1.33% of “Our Price”?
Low miles, one owner, and no accident history! 
Third row SUV kept in great shape. 
Can this section include the Drivetrain and Body Style information from the vehicle data? An example would be: “FWD Sedan kept in great shape.” Or “4WD SUV kept in great shape.”
No rust or tears in the interior. 
SLE trim level includes heated seating, backup camera, keyless entry remote, Bluetooth, USB plugin, MP3 auxiliary phone plugin, and more. 
Can the “SLE trim” be an insert from whatever data is in the trim section of the vehicle information? If no trim data is entered than remove the “SLE” and just begin the sentence with “Trim”.
Warranty included! 
Can we have “Warranty included!” display only if the vehicle is 10 years old or newer and under 100,000 miles?
Call or text Tim with any questions or to schedule a test drive: 651-447-7908
	Please remove the name 😊
FAMILY OWNED | FAMILY FOCUSED Royal Drive is a car dealership located in Newport, MN (9 miles from St. Paul) that sells restored insurance-claimed vehicles including hail dents, tree dents, or light collision for a better price to help families find their Royal Drive. We do not sell any vehicles with flood damage or extensive frame damage. Text us for the pre-repair pictures to see what was repaired! 
	The text above has been changed too. Please update 😊

**Comment by JacobWeisenburger** [comment]
Sounds good. Will do

**Comment by RoyalDrive** [comment]
SO COOL We love it!!!!! THANK YOU

Are you able to correct a few small paste errors? Some of the words don't have a space between them.

![image](https://user-images.githubusercontent.com/79367027/162833332-ad971a17-0fff-4e35-a6ba-876782840b5a.png)

**Comment by JacobWeisenburger** [comment]
will do
