### ISSUE TITLE
Projected Year End Revenue

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#123]
A nice to have would be a simple calculator that projects the year's end gross profit by the following formula:

 - Calculate YTD gross profit (example: $1,000,000, 165 days into year)
 - divide YTD gross profit by number of days into year (example: 1,000,000 / 165 = 6,060.60)
 - multiply calculated number by days remaining in the year (example: 6,060.60 x 200 = 1,212,121.21)
 - combine YTD gross profit by multiplied calculated number of days remaining (1,000,000 + 1,212,121.21 = 2,212,121.21)
 - display calculated number as projected year's end gross profit (2,212,121.21)

:-)

**Comment by RoyalDrive** [comment]
Yes, Gross/Revenue

**Comment by RoyalDrive** [comment]
Gross profit is the same thing as revenue. Net profit is different but they're two types of profit displayed on a balance sheet.

**Comment by JacobWeisenburger** [comment]
according to the internet:
Gross Profit = Revenue − Cost of Goods Sold
(https://www.investopedia.com/terms/g/grossprofit.asp)

​So basically, we are both wrong. I didn't realize gross profit is a thing, however gross profit is NOT the same thing as revenue.
Are you wanting Gross Profit? Gross Profit = Revenue − Total Investment
Or are you wanting just Revenue?
