### ISSUE TITLE
Website Template should only show Clean or Rebuilt

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#125]
Hey Jake,

On the Website Template button where it copies the title status can we have it just say the words "Rebuilt title" instead of Salvage?

![image](https://user-images.githubusercontent.com/79367027/177834062-46f737eb-c207-41ef-bac7-f2609ada55f2.png)

**Comment by JacobWeisenburger** [comment]
so if it's Clean then it shows Clean, but if it's anything else it should show Rebuilt?

**Comment by RoyalDrive** [comment]
Correct!
