### ISSUE TITLE
DMS 2.0 Ideas

### ISSUE THREAD

**Issue by JacobWeisenburger** [Royal-Drive/DMS#127]
From Tim:
- a section for test drive notes/comments
- a button that will load the vehicle folder(not sure that's possible) or at least copy the lot #
- add more space for a Parts expense in the description
- add a category for cars that are listed but need a repair and if they are drivable and expected fix by date
- we no longer have use for the Craigslist template;
- I use the search bar most often. I usually search the vehicle using the model name.
- I use some of the filters on the left.
- could be helpful if you could search for sold cars without clicking the sold filter

**Comment by RoyalDrive** [comment]
Comment on the issues listed above:
- We will still require the color code box to be left. Every other comment is spot on.

**Comment by JacobWeisenburger** [comment]
This issue has been moved to a discussion https://github.com/Royal-Drive/DMS/discussions/131
