### ISSUE TITLE
Royal Drive Access Security

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#129]
Notes on maintaining file security and different levels of access per user.

IDEAS:
- each user get a different Google account with their own email/bookmarks
- each user have a different email for logging into the DMS

**Comment by JacobWeisenburger** [comment]
You don't need to sign the front desk computer out every time you start using it, you could just use whatever account is signed in, but I just think that only you and maybe me should know the password to the info@royaldrive account.

**Comment by JacobWeisenburger** [comment]
This issue has been moved to a discussion https://github.com/Royal-Drive/DMS/discussions/130
