### ISSUE TITLE
Allow more than 1 Acquisition

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#20]
since each page URL is the VIN, what happens when we get the same car uploaded twice? It has happened more recently than earlier: sell a car and the same customer trades it in a year later for an upgrade.

![image](https://user-images.githubusercontent.com/79367027/108603920-4b318500-7370-11eb-97ef-706bc5c80101.png)

**Comment by RoyalDrive** [comment]
Can we update this to be a billable work order? We're beginning to get return vehicles. Have sold 2 cars this year already that we sold to a customer several years ago and they're now trading it in.

**Comment by JacobWeisenburger** [comment]
all you gotta do is add a priority.
