### ISSUE TITLE
Fix bugs in the Listing section

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#70]
Starting to spot a couple bugs in the listing section:

Some cars only display:
![image](https://user-images.githubusercontent.com/79367027/110967592-2baccd00-831c-11eb-8199-4872a3dec0b3.png)

And new cars don't display anything but just spin the loader:
![image](https://user-images.githubusercontent.com/79367027/110967850-72022c00-831c-11eb-8c89-973602434f9a.png)

Should be: 
![image](https://user-images.githubusercontent.com/79367027/110967547-1b94ed80-831c-11eb-958c-dd5d59c86551.png)

**Comment by JacobWeisenburger** [comment]
Pretty sure this got fixed by accident. Let me know if this is still a problem.
