### ISSUE TITLE
Tim & My Computers are displaying different numbers for the Salvage category.

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#77]
Pic for example. Not the biggest problem so not super urgent. 

![image](https://user-images.githubusercontent.com/79367027/112884979-c97ef680-9095-11eb-9dc8-ad7afa1bfb60.png)

**Comment by JacobWeisenburger** [comment]
I think it was just a 1 time "out of sync" error. Simple fix.
