### ISSUE TITLE
Add/Change Filters

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#80]
Hey Jake, couple edits to make on filters.

Can you add a few filters and sort the filters into categories? 

WORK ORDER
 - Unassigned
 - In-Transit
 - Onsite Repairs
 - Offsite Repairs
 - Detailing

TITLE
 - Clean
 - Salvage: Out of State
 - Salvage: Minnesota
 - Salvage: MN Inspected
 - Rebuilt

SALE
 - Unlisted
 - Listed
 - Consignment
 - Sold

![image](https://user-images.githubusercontent.com/79367027/112900317-f25cb700-90a8-11eb-9728-fca72f541ba4.png)

**Comment by JacobWeisenburger** [comment]
do you want Unassigned to be included with this change?

**Comment by RoyalDrive** [comment]
Yes! I actually have it as a work order as well :D 

You can go ahead and make it a status in the vehicle page as well. I like your idea about having "Unassigned" and "Unlisted" being auto-selected by default. 


![image](https://user-images.githubusercontent.com/79367027/113779663-ad153680-96f3-11eb-9c4a-a4be47229a1b.png)

**Comment by RoyalDrive** [comment]
Can we add filter sections titled: WORK ORDER, TITLE, and SALE

**Comment by JacobWeisenburger** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/31667350/114073438-e4592400-9868-11eb-96c8-2b8fdf395da3.png)

**Comment by RoyalDrive** [comment]
Go for it!!
