### ISSUE TITLE
Please remove Listed vehicles from the Unassigned filter

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#87]
Please remove vehicles from the Unassigned filter if they are listed and have DOM as a status.

**Comment by JacobWeisenburger** [comment]
I feel like this was taken care of by another ticket. Or is there something that still needs to be done for this issue?

**Comment by RoyalDrive** [comment]
Yes! Please remove all LISTED cars in the Unassigned filter. 

![image](https://user-images.githubusercontent.com/79367027/117189213-89e9af80-ada3-11eb-90b5-abbdab9f1237.png)

**Comment by RoyalDrive** [comment]
I just want the Unassigned filter to display what I can "true unassigned" vehicles which means they are UNNASSIGNED and UNLISTED.
