### ISSUE TITLE
Title Tracker Feature

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#90]
#### Dev Notes:
- Use button toggle group
- Selected option: green background
---

- This is a feature that is super similar to Domino's online pizza tracker!
- The drop down menu displaying title statuses will have: Salvage, Clean, and Rebuilt (Prior Salvage).
- This tracker menu will only pop up when the "Salvage" option is selected.
- The following salvage menu items will be displayed in this order:
   - Not Arrived
   - Submitted to DMV 
   - Prep for Inspection
   - Ready to Inspect
   - Inspected

![Salvage](https://user-images.githubusercontent.com/79367027/116937972-a8c73500-ac2f-11eb-8cf5-86ae6a081917.png)

**Comment by JacobWeisenburger** [comment]
I'm super close to being done with this, ran out of time today, but I should have it ready tomorrow.

**Comment by RoyalDrive** [comment]
Woohoo! :D
