### ISSUE TITLE
Visibility & Edit access for On-Site Repair filter only

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#95]
Was brainstorming a way for our mechanic to be able to have  a live feed of repair projects and I think this is the best approach I've come up with so far.

A login access that can only view and edit the vehicles in the On-Site repair filter. Edit access for anything on the page for now would be fine and maybe a future update could be select sections are editable and others are not. 

Thoughts? :)

**Comment by JacobWeisenburger** [comment]
- [x] Make read only access for Fernando
   - Any one can use the site right now with read only access, so Fernando could already start using it to not need the printed pages
- [ ] Allow edit access for Fernando
- [ ] Allow edit access for Fernando for only certain things

**Comment by RoyalDrive** [comment]
Correction: Make read only for just the On-Site repair filter.

**Comment by JacobWeisenburger** [comment]
so you are saying you don't want him to be able to view any cars that are not Onsite repair?

**Comment by RoyalDrive** [comment]
That's correct!

**Comment by JacobWeisenburger** [comment]
just have him hit the onsite repair filter

**Comment by RoyalDrive** [comment]
Coming back around to this issue.

I think it's fine if Fernando has view access to the whole vehicle page but no edit access. I don't care if he sees all the data inside the vehicle page list as long as the list of vehicles he views is only the Onsite Repair filter view.

**Comment by JacobWeisenburger** [comment]
> Coming back around to this issue.
> 
> I think it's fine if Fernando has view access to the whole vehicle page but no edit access. I don't care if he sees all the data inside the vehicle page list as long as the list of vehicles he views is only the Onsite Repair filter view.

If you are fine with Fernando being able to see everything, but not being able to edit anything, then I don't think anything needs to change, because I'm pretty sure that is already in place. Let me know if it is not working that way.

**Comment by RoyalDrive** [comment]
You're correct, he can see the data without editing it. What I need is a separate link to just be able to view the Onsite Repair tab ONLY without visibility to any other data or filters.

**Comment by JacobWeisenburger** [comment]
Moved to Role Based Access #106
