### ISSUE TITLE
Update Title Filters

### ISSUE THREAD

**Issue by RoyalDrive** [Royal-Drive/DMS#98]
Once the salvage status tracker is completed please update the title filters on the home page of the DMS to be the following in this order:

 - No Title (Not Arrived AND/OR At the Auction as the location)
 - Clean
 - Rebuilt
 - Prep for Inspection (do not display vehicles with Onsite OR Offsite IF vehicle is Unlisted)
 - Ready to Inspect
 - Inspected

Any other title filters can be removed.

**Comment by JacobWeisenburger** [comment]
what are you wanting "No Title" to do? show cars that don't have a title status?

**Comment by RoyalDrive** [comment]
Thanks for clarifying.

No title: anything that has Not Arrived AND/OR At the Auction as the location

![image](https://user-images.githubusercontent.com/79367027/117364006-03a49a80-ae83-11eb-91e9-caaf209a0a1f.png)

**Comment by RoyalDrive** [comment]
Or you can make it simple at just have it be the "Not Arrived" button. Whatever is easier.

**Comment by JacobWeisenburger** [comment]
I think making it "if the car has Not Arrived OR At the Auction" should be easy.

**Comment by RoyalDrive** [comment]
Sweet. Let's do it! Also, I updated the post up above with another edit.
